# Generated by Django 5.2.2 on 2025-06-25 16:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('valeur', models.TextField()),
                ('type_valeur', models.CharField(choices=[('string', 'Chaîne de caractères'), ('integer', 'Nombre entier'), ('float', 'Nombre décimal'), ('boolean', 'Booléen'), ('json', 'JSON')], default='string', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('modifiable', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parametres_systeme',
                'ordering': ['cle'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('transporteur', 'Transporteur'), ('planificateur', 'Planificateur')], max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origine', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('description_marchandise', models.TextField()),
                ('poids', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateTimeField()),
                ('date_livraison_planifiee', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('affectee', 'Affectée'), ('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('distance_estimee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duree_estimee', models.DurationField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_client', to='utilisateurs.user')),
                ('planificateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_planifiees', to='utilisateurs.user')),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_transporteur', to='utilisateurs.user')),
            ],
            options={
                'db_table': 'commandes',
                'ordering': ['-date_creation'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(choices=[('camionnette', 'Camionnette'), ('camion', 'Camion'), ('semi_remorque', 'Semi-remorque')], max_length=20)),
                ('capacite_max', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('disponible', models.BooleanField(default=True)),
                ('marque', models.CharField(blank=True, max_length=50, null=True)),
                ('modele', models.CharField(blank=True, max_length=50, null=True)),
                ('annee', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('couleur', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='utilisateurs.user')),
            ],
            options={
                'db_table': 'vehicules',
                'ordering': ['-date_ajout'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_debut_prevue', models.DateTimeField()),
                ('date_fin_prevue', models.DateTimeField()),
                ('date_debut_reelle', models.DateTimeField(blank=True, null=True)),
                ('date_fin_reelle', models.DateTimeField(blank=True, null=True)),
                ('distance_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duree_prevue', models.DurationField(blank=True, null=True)),
                ('duree_reelle', models.DurationField(blank=True, null=True)),
                ('optimisee', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('planificateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournees_planifiees', to='utilisateurs.user')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournees_assignees', to='utilisateurs.user')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournees', to='utilisateurs.vehicule')),
            ],
            options={
                'db_table': 'tournees',
                'ordering': ['-date_creation'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('incident', 'Incident')], default='en_attente', max_length=20)),
                ('position_actuelle', models.CharField(blank=True, max_length=200)),
                ('latitude_actuelle', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude_actuelle', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('notes_livraison', models.TextField(blank=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='utilisateurs.commande')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='utilisateurs.tournee')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='utilisateurs.vehicule')),
            ],
            options={
                'db_table': 'livraisons',
                'ordering': ['-commande__date_creation'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EtapeTournee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordre', models.IntegerField()),
                ('type_etape', models.CharField(choices=[('depot', 'Dépôt'), ('collecte', 'Collecte'), ('livraison', 'Livraison'), ('pause', 'Pause')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('retard', 'En retard'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('adresse', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('heure_prevue', models.DateTimeField()),
                ('heure_arrivee', models.DateTimeField(blank=True, null=True)),
                ('heure_depart', models.DateTimeField(blank=True, null=True)),
                ('duree_prevue', models.DurationField()),
                ('duree_reelle', models.DurationField(blank=True, null=True)),
                ('distance_precedente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapes_tournee', to='utilisateurs.commande')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='utilisateurs.tournee')),
            ],
            options={
                'db_table': 'etapes_tournee',
                'ordering': ['tournee', 'ordre'],
                'managed': True,
                'unique_together': {('tournee', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('nouvelle_commande', 'Nouvelle commande'), ('commande_affectee', 'Commande affectée'), ('commande_planifiee', 'Commande planifiée'), ('tournee_creee', 'Tournée créée'), ('statut_livraison', 'Statut livraison'), ('incident', 'Incident'), ('system', 'Système')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='utilisateurs.commande')),
                ('livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='utilisateurs.livraison')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='utilisateurs.tournee')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='utilisateurs.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-date_creation'],
                'managed': True,
                'indexes': [models.Index(fields=['utilisateur', '-date_creation'], name='notificatio_utilisa_546e26_idx'), models.Index(fields=['lu', '-date_creation'], name='notificatio_lu_fd634b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('status_change', 'Changement de statut'), ('assignment', 'Affectation'), ('planning', 'Planification')], max_length=20)),
                ('description', models.TextField()),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('ancien_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='utilisateurs.user')),
            ],
            options={
                'db_table': 'historique_actions',
                'ordering': ['-date_action'],
                'managed': True,
                'indexes': [models.Index(fields=['utilisateur', '-date_action'], name='historique__utilisa_4340ff_idx'), models.Index(fields=['table_name', 'record_id'], name='historique__table_n_d5e8e3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut', 'date_creation'], name='commandes_statut_beb3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['transporteur', 'statut'], name='commandes_transpo_824d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['planificateur', 'statut'], name='commandes_planifi_1e5a66_idx'),
        ),
    ]
