# Generated by Django 5.2.2 on 2025-06-08 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('type_vehicule', models.CharField(max_length=100)),
                ('capacite_charge', models.FloatField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('AFFECTEE', 'Affectée'), ('EN_TRANSIT', 'En transit'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('poids', models.FloatField()),
                ('type_marchandise', models.CharField(max_length=100)),
                ('adresse_enlevement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_enlevement', to='transport.adresse')),
                ('adresse_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_livraison', to='transport.adresse')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.client')),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.transporteur')),
            ],
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_intermediaires', models.JSONField(blank=True, default=list)),
                ('distance', models.FloatField()),
                ('temps_estime', models.IntegerField()),
                ('point_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraires_arrivee', to='transport.adresse')),
                ('point_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraires_depart', to='transport.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.commande')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporteur')),
            ],
        ),
    ]
