# Generated by Django 5.2.2 on 2025-06-19 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonneesMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('conditions', models.CharField(max_length=50)),
                ('vent_vitesse', models.FloatField()),
                ('vent_direction', models.CharField(blank=True, max_length=10)),
                ('visibilite', models.IntegerField()),
                ('precipitation', models.FloatField(default=0)),
                ('alerte', models.BooleanField(default=False)),
                ('niveau_alerte', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonneesTrafic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.CharField(choices=[('fluide', 'Fluide'), ('normal', 'Normal'), ('dense', 'Dense'), ('bloque', 'Bloqué')], default='normal', max_length=20)),
                ('vitesse_moyenne', models.FloatField()),
                ('temps_retard', models.IntegerField(default=0)),
                ('incidents', models.JSONField(blank=True, default=list)),
                ('routes_affectees', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ParametreSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('valeur', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='signature_client',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='commande',
            name='priorite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='type_route',
            field=models.CharField(default='nationale', max_length=50),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='derniere_maj_position',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='latitude_actuelle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='longitude_actuelle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissionTransporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ASSIGNEE', 'Assignée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='ASSIGNEE', max_length=20)),
                ('itineraire_optimise', models.JSONField(blank=True, default=dict)),
                ('distance_parcourue', models.FloatField(default=0)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.commande')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporteur')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('PANNE', 'Panne véhicule'), ('RETARD', 'Retard'), ('MARCHANDISE', 'Problème marchandise'), ('METEO', 'Conditions météo'), ('AUTRE', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incidents/')),
                ('resolu', models.BooleanField(default=False)),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporteur')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.missiontransporteur')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MISSION', 'Nouvelle mission'), ('STATUT', 'Changement de statut'), ('INCIDENT', 'Incident signalé'), ('SYSTEME', 'Message système')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute')], default='NORMALE', max_length=10)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.commande')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL)),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.transporteur')),
            ],
        ),
    ]
