# Generated by Django 5.0.1 on 2025-06-22 17:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_parametresysteme_type_supportmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTransporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_ponctualite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_professionnalisme', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_etat_marchandise', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_globale', models.FloatField()),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Évaluation transporteur',
                'verbose_name_plural': 'Évaluations transporteurs',
            },
        ),
        migrations.AlterModelOptions(
            name='adresse',
            options={'ordering': ['ville', 'rue'], 'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='bonlivraison',
            options={'verbose_name': 'Bon de livraison', 'verbose_name_plural': 'Bons de livraison'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='donneesmeteo',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Données météo', 'verbose_name_plural': 'Données météo'},
        ),
        migrations.AlterModelOptions(
            name='donneestrafic',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Données trafic', 'verbose_name_plural': 'Données trafic'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date_signalement'], 'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
        migrations.AlterModelOptions(
            name='itineraire',
            options={'verbose_name': 'Itinéraire', 'verbose_name_plural': 'Itinéraires'},
        ),
        migrations.AlterModelOptions(
            name='journalactivite',
            options={'ordering': ['-date'], 'verbose_name': "Journal d'activité", 'verbose_name_plural': "Journal d'activité"},
        ),
        migrations.AlterModelOptions(
            name='missiontransporteur',
            options={'ordering': ['-date_assignation'], 'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='parametresysteme',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': 'Paramètre système', 'verbose_name_plural': 'Paramètres système'},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['-date_envoi'], 'verbose_name': 'Message support', 'verbose_name_plural': 'Messages support'},
        ),
        migrations.AlterModelOptions(
            name='transporteur',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Transporteur', 'verbose_name_plural': 'Transporteurs'},
        ),
        migrations.AddField(
            model_name='adresse',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='date_livraison_effective',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='photo_livraison',
            field=models.ImageField(blank=True, null=True, upload_to='livraisons/'),
        ),
        migrations.AddField(
            model_name='bonlivraison',
            name='signature_transporteur',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='client',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='date_livraison_souhaitee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='instructions_speciales',
            field=models.TextField(blank=True, verbose_name='Instructions spéciales'),
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_estime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix estimé'),
        ),
        migrations.AddField(
            model_name='incident',
            name='date_resolution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='gravite',
            field=models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Élevée'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=10),
        ),
        migrations.AddField(
            model_name='incident',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='cout_carburant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='peages',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='itineraire',
            name='polyline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalactivite',
            name='objet_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalactivite',
            name='objet_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalactivite',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missiontransporteur',
            name='commentaire_client',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missiontransporteur',
            name='date_acceptation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missiontransporteur',
            name='note_client',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note du client'),
        ),
        migrations.AddField(
            model_name='missiontransporteur',
            name='temps_reel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temps réel (minutes)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametresysteme',
            name='categorie',
            field=models.CharField(default='Général', max_length=50),
        ),
        migrations.AddField(
            model_name='parametresysteme',
            name='modifiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='support/'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='priorite',
            field=models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='statut',
            field=models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('FERME', 'Fermé')], default='NOUVEAU', max_length=20),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='sujet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporteur',
            name='note_moyenne',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Note moyenne'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='code_postal',
            field=models.CharField(max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='pays',
            field=models.CharField(default='Maroc', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='rue',
            field=models.CharField(max_length=255, verbose_name='Rue'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='bonlivraison',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('SIGNE', 'Signé'), ('TERMINE', 'Terminé')], default='EN_COURS', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='poids',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Poids (kg)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='priorite',
            field=models.IntegerField(choices=[(0, 'Normale'), (1, 'Haute'), (2, 'Urgente')], default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type_marchandise',
            field=models.CharField(max_length=100, verbose_name='Type de marchandise'),
        ),
        migrations.AlterField(
            model_name='donneesmeteo',
            name='conditions',
            field=models.CharField(choices=[('ENSOLEILLE', 'Ensoleillé'), ('NUAGEUX', 'Nuageux'), ('PLUIE', 'Pluie'), ('NEIGE', 'Neige'), ('BROUILLARD', 'Brouillard'), ('ORAGE', 'Orage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donneesmeteo',
            name='precipitation',
            field=models.FloatField(default=0, verbose_name='Précipitations (mm)'),
        ),
        migrations.AlterField(
            model_name='donneesmeteo',
            name='temperature',
            field=models.FloatField(verbose_name='Température (°C)'),
        ),
        migrations.AlterField(
            model_name='donneesmeteo',
            name='vent_vitesse',
            field=models.FloatField(verbose_name='Vitesse du vent (km/h)'),
        ),
        migrations.AlterField(
            model_name='donneesmeteo',
            name='visibilite',
            field=models.IntegerField(verbose_name='Visibilité (m)'),
        ),
        migrations.AlterField(
            model_name='donneestrafic',
            name='niveau',
            field=models.CharField(choices=[('FLUIDE', 'Fluide'), ('NORMAL', 'Normal'), ('DENSE', 'Dense'), ('BLOQUE', 'Bloqué')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='donneestrafic',
            name='temps_retard',
            field=models.IntegerField(default=0, verbose_name='Retard estimé (min)'),
        ),
        migrations.AlterField(
            model_name='donneestrafic',
            name='vitesse_moyenne',
            field=models.FloatField(verbose_name='Vitesse moyenne (km/h)'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('ACCIDENT', 'Accident'), ('PANNE', 'Panne véhicule'), ('RETARD', 'Retard'), ('MARCHANDISE', 'Problème marchandise'), ('METEO', 'Conditions météo'), ('TRAFIC', 'Problème de trafic'), ('CLIENT', 'Problème client'), ('AUTRE', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='distance',
            field=models.FloatField(verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='itineraire',
            name='temps_estime',
            field=models.IntegerField(verbose_name='Temps estimé (minutes)'),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('ASSIGN', 'Affectation'), ('COMPLETE', 'Finalisation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='missiontransporteur',
            name='distance_parcourue',
            field=models.FloatField(default=0, verbose_name='Distance parcourue (km)'),
        ),
        migrations.AlterField(
            model_name='missiontransporteur',
            name='statut',
            field=models.CharField(choices=[('ASSIGNEE', 'Assignée'), ('ACCEPTEE', 'Acceptée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='ASSIGNEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priorite',
            field=models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MISSION', 'Nouvelle mission'), ('STATUT', 'Changement de statut'), ('INCIDENT', 'Incident signalé'), ('SYSTEME', 'Message système'), ('PROMOTION', 'Promotion'), ('RAPPEL', 'Rappel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parametresysteme',
            name='type',
            field=models.CharField(choices=[('STRING', 'Texte'), ('INTEGER', 'Entier'), ('FLOAT', 'Décimal'), ('BOOLEAN', 'Booléen'), ('JSON', 'JSON')], default='STRING', max_length=20),
        ),
        migrations.AlterField(
            model_name='parametresysteme',
            name='valeur',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='capacite_charge',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Capacité de charge (kg)'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='derniere_maj_position',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière MAJ position'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='latitude_actuelle',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude actuelle'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='longitude_actuelle',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude actuelle'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='matricule',
            field=models.CharField(max_length=50, unique=True, verbose_name='Matricule véhicule'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='type_vehicule',
            field=models.CharField(choices=[('CAMION_3T5', 'Camion 3.5T'), ('CAMION_7T5', 'Camion 7.5T'), ('CAMION_12T', 'Camion 12T'), ('CAMION_20T', 'Camion 20T'), ('SEMI_REMORQUE', 'Semi-remorque'), ('FOURGON', 'Fourgon'), ('UTILITAIRE', 'Utilitaire')], max_length=20, verbose_name='Type de véhicule'),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='missiontransporteur',
            unique_together={('commande', 'transporteur')},
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut'], name='transport_c_statut_bcf010_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['date_creation'], name='transport_c_date_cr_5c7f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['client'], name='transport_c_client__976374_idx'),
        ),
        migrations.AddIndex(
            model_name='journalactivite',
            index=models.Index(fields=['utilisateur'], name='transport_j_utilisa_228b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalactivite',
            index=models.Index(fields=['date'], name='transport_j_date_d6edbf_idx'),
        ),
        migrations.AddIndex(
            model_name='journalactivite',
            index=models.Index(fields=['action'], name='transport_j_action_fa051f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', 'lu'], name='transport_n_destina_abd3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['date_creation'], name='transport_n_date_cr_fb9bde_idx'),
        ),
        migrations.AddField(
            model_name='evaluationtransporteur',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.client'),
        ),
        migrations.AddField(
            model_name='evaluationtransporteur',
            name='mission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transport.missiontransporteur'),
        ),
        migrations.AddField(
            model_name='evaluationtransporteur',
            name='transporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transporteur'),
        ),
    ]
